{% set version = "2.3.2" %}
{% set sha256 = "70f7cfd02e8032c4641fd0facfe25a6f8021bd1a18d7d1d25e566bfdbe988095" %}
{% set libgd_version = "2.3.*" %}

package:
  name: py_gd
  version: {{ version }}

source:
  fn: py_gd-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/py_gd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgd {{ libgd_version }}              # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libgd {{ libgd_version }}
    - cython >=3
    - numpy

  run:
    - python
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible('libgd') }}

test:
  requires:
    - pytest
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: CC0-1.0
  license_file: LICENSE.txt
  summary: Pythonic wrappers for the libgd graphics rendering library

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
