schema_version: 1

context:
  version: 2.3.3
  libgd_version: 2.3.*

package:
  name: py_gd
  version: ${{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/py_gd/archive/v${{ version }}.tar.gz
  sha256: 492227ac6d8f30bb70e73d86bcf4580dc5de2683883db5ca02c95803fb54a3be

build:
  number: 0
  script: ${{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
        - numpy
        - cython >=3
        - libgd ${{ libgd_version }}
    - make
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - libgd ${{ libgd_version }}
    - cython >=3
    - numpy
    - scikit-build-core
    - cython-cmake
  run:
    - python >=3.10
    - numpy
    - ${{ pin_compatible('libgd') }}

tests:
  - python:
      imports:
        - py_gd
  - requirements:
      run:
        - pytest
    script:
      - pytest --pyargs py_gd

about:
  license: CC0-1.0
  license_file: LICENSE.txt
  summary: Pythonic wrappers for the libgd graphics rendering library
  homepage: https://github.com/NOAA-ORR-ERD/py_gd

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
